# Generated by Django 2.1.1 on 2018-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='краткое содержание')),
                ('content', models.TextField(verbose_name='полное содержание')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='опубликована')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-posted'],
            },
        ),
    ]
