# Generated by Django 2.1.1 on 2018-09-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolls',
            options={'verbose_name': 'ролл', 'verbose_name_plural': 'rolls'},
        ),
        migrations.AlterModelOptions(
            name='sets',
            options={'verbose_name': 'сет', 'verbose_name_plural': 'sets'},
        ),
        migrations.AlterModelOptions(
            name='soups',
            options={'verbose_name': 'суп', 'verbose_name_plural': 'soups'},
        ),
        migrations.AlterModelOptions(
            name='sushi',
            options={'verbose_name': 'суши', 'verbose_name_plural': 'sushi'},
        ),
    ]
