# Generated by Django 2.1.1 on 2018-09-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа')),
                ('food', models.ForeignKey(on_delete='', to='menu.Rolls', verbose_name='еда')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа')),
                ('food', models.ForeignKey(on_delete='', to='menu.Sets', verbose_name='еда')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSoup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа')),
                ('food', models.ForeignKey(on_delete='', to='menu.Soups', verbose_name='еда')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа')),
                ('food', models.ForeignKey(on_delete='', to='menu.Sushi', verbose_name='еда')),
            ],
        ),
    ]
